baseURL: https://bludwarf.github.io/blog-chroniques-oubliees/
disablePathToLower: true
languageCode: fr
DefaultContentLanguage: fr
SectionPagesMenu: main
title: Journal de bord des Chroniques Oubliées
theme: "ananke"

taxonomies:
  auteur: auteurs

params:
  description: Journal de bord des Chroniques Oubliées
  background_color_class: bg-dark-gray
  body_classes: "avenir bg-washed-yellow"
  show_reading_time: false
  mainSections:
  - "partie"
  recent_posts_number: 5
  featured_image: /assets/dessins/Mathieu/1.jpg
  commentoEnable: false