baseURL: https://bludwarf.github.io/blog-chroniques-oubliees-hugo/
disablePathToLower: true
languageCode: fr
DefaultContentLanguage: fr
SectionPagesMenu: main
title: Journal de bord des Chroniques Oubliées
theme: "ananke"

params:
  background_color_class: bg-dark-gray
  body_classes: "avenir bg-washed-yellow"